baseUrl: https://blog.dohoang.me 
languageCode: en-us
theme: hello-friend
copyright: '&copy; Do Hoang. All rights reserved.'
paginate: 5

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # "dark" or "light"
  defaultTheme: light
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 3
  showReadingTime: false
languages:
  en:
    title: Do Hoang
    subtitle: Software developer
    keywords: 'Software Dev, Blog'
    menuMore: Show more
    writtenBy: Written by
    readMore: Read more
    readOtherPosts: Read other posts
    newerPosts: Newer posts
    olderPosts: Older posts
    dateFormatSingle: 2006-01-02
    dateFormatList: 2006-01-02
    
    params:
      logo:
        logoText: $ cd /home/kn
        logoHomeLink: /
    #   or
    #
    #   path: /img/your-example-logo.svg
    #   alt: Your example logo alt text
    
    menu:
      main:
      - identifier: about
        name: About
        url: "https://dohoang.me" 
      - identifier: blog
        name: Blog
        url: /
      - identifier: showcase
        name: Showcase
        url: /showcase
