baseUrl: /
languageCode: en-us
theme: terminal
paginate: 5
DefaultContentLanguage: en

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: green
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 3
  # show selector to switch language
  showLanguageSelector: true
  # set theme to full screen width
  fullWidthTheme: false
  # center theme with default width
  centerTheme: false
  # favicon: /favicon.ico

languages:
  en:
    languageName: english
    title: Kn
    subtitle: Anything that's software
    tagline: A software blog that runs in the true spirit of open-source
    keywords: 'blog, software, software-engineering, technology, code'
    menuMore: show more
    readMore: read more
    readOtherPosts: read other posts

    params:
      logo:
        logoText: Kn
        logoHomeLink: /

    menu:
      main:
        - identifier: about
          name: about
          url: https://huyhoang8398.github.io
  vi:
    languageName: viet
    title: Kn
    subtitle: Miễn là phần mềm
    tagline: Blog về phần mềm hoạt động trên tinh thần open-source
    keywords: 'blog, software, phần-mềm, công-nghệ, code'
    keywords: ''
    menuMore: xem thêm
    readMore: đọc thêm
    readOtherPosts: đọc bài khác

    params:
      logo:
        logoText: Kn
        logoHomeLink: /vi

    menu:
      main:
        - identifier: about
          name: giới thiệu
          url: https://huyhoang8398.github.io

taxonomies:
  author: authors
  tag: tags